[package]
name = "tracker"
version = "0.1.1"
edition = "2021"
repository = "https://github.com/ajrussellaudio/tracker"

[[bin]]
name = "tracker"
path = "src/main.rs"

[dependencies]
tracker-core = { path = "../tracker-core" }
anyhow = "1.0"
ratatui = "0.29"
crossterm = "0.28"
cpal = "0.15"
hound = "3.5"
rtrb = "0.3"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
